config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users

  resources :profiles do
    resources :articles
    resources :donations
    resources :reviews
    resources :meetings
    resources :messages
  end
  resources :orders, only: [:show, :new, :create] do
    resources :payments, only: [:new, :create]
  end
  resources :charges
  root to: 'pages#home'
  get 'citywithdept', to: 'profiles#citywithdept'
  get 'dentistwithcity', to: 'profiles#dentistwithcity'
  get 'getSearch', to: 'profiles#getSearch'

  get 'excelcreator', to: 'profiles#excelcreator'

  get 'valider_article', to: 'articles#valider_article'
  get 'refuser_article', to: 'articles#refuser_article'
  get 'valider_review', to: 'reviews#valider_review'
  get 'refuser_review', to: 'reviews#refuser_review'
  get 'pages/about'
  get 'pages/formation'
  get 'pages/formation1'
  get 'pages/test'
  get 'pages/partnerships'
  get 'reviews/all'
  get 'articles/all'
  get 'pages/soins'
  get 'pages/all_articles_categories'
  get 'pages/make_a_donation'
  get 'pages/support_us'
  get 'pages/conversation'
  get 'pages/demande_rdv'
  get 'pages/conversationitem'

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_articlesall.html.erb
<% @articles.each do |article| %>
  <% @profile = Profile.find(article.profile_id)  %>
  <div class="cell-sm-6">
    <!-- Post Modern-->
    <article class="post post-modern post-modern-classic">
      <!-- Post media-->
      <header class="post-media"><%= image_tag article.article_photo, width:"370", height:"240", class:"img-responsive img-cover" %>
      </header>
      <!-- Post content-->
      <section class="post-content text-left">
        <!-- Post Title-->
        <div class="post-title offset-top-8">
          <h4 class="text-bold"> <%= link_to article.article_title, profile_article_path(@profile, article)%> </h4>
        </div>
        <ul class="list-inline list-inline-dashed">
          <li><%= article.created_at.strftime("%d.%m.%Y") %></li>
          <li><i  class="text-secondary"><%=article.theme%></i></li>
        </ul>
        <!-- Post Body-->
        <div class="post-body" style="margin-bottom: 30px;">
          <p><%= article.article_content.first(200) %> ...</p>
        </div>
      </section>
    </article>
  </div>
<% end  %>

app/views/shared/_articlesevenement.html.erb
<% i = 0  %>
<% if Article.where(theme: "Evènement") == [] %>
  <div class="cell-sm-6">
    <!-- Post Modern-->
    <article class="post post-modern post-modern-classic">
      <section class="post-content text-left">
        <!-- Post Title-->
        <div class="post-title offset-top-8">
          <p class="text-bold">Aucun article de cette catégorie n'a été rédigé pour le moment</p>
        </div>
      </section>
    </article>
  </div>
<% end  %>
<% @articles.where(status: 'Validé').order("created_at DESC").each do |article| %>
  <% if article.theme == "Evènement" && i < 3 %>
    <% i = i + 1  %>
    <% @profile = Profile.find(article.profile_id)  %>
    <div class="cell-sm-6">
      <!-- Post Modern-->
      <article class="post post-modern post-modern-classic">
        <!-- Post media-->
        <header class="post-media"><%= image_tag article.article_photo, width:"370", height:"240", class:"img-responsive img-cover" %>
        </header>
        <!-- Post content-->
        <section class="post-content text-left">
          <!-- Post Title-->
          <div class="post-title offset-top-8">
            <h4 class="text-bold"> <%= link_to article.article_title, profile_article_path(@profile, article)%> </h4>
          </div>
          <ul class="list-inline list-inline-dashed">
            <li><%= article.created_at.strftime("%d.%m.%Y") %></li>
            <li><i  class="text-secondary"><%=article.theme%></i></li>
          </ul>
          <!-- Post Body-->
          <div class="post-body" style="margin-bottom: 30px;">
            <p><%= article.article_content.first(200) %> ...</p>
          </div>
        </section>
      </article>
    </div>
  <% end  %>
<% end %>

app/views/shared/_articlesmeopa.html.erb
<% i = 0  %>
<% if Article.where(theme: "Meopa") == [] %>
  <div class="cell-sm-6">
    <!-- Post Modern-->
    <article class="post post-modern post-modern-classic">
      <section class="post-content text-left">
        <!-- Post Title-->
        <div class="post-title offset-top-8">
          <p class="text-bold">Aucun article de cette catégorie n'a été rédigé pour le moment</p>
        </div>
      </section>
    </article>
  </div>
<% end  %>
<% @articles.where(status: 'Validé').order("created_at DESC").each do |article| %>
  <% if article.theme == "Meopa" && i < 3 %>
    <% i = i + 1  %>
    <% @profile = Profile.find(article.profile_id)  %>
    <div class="cell-sm-6">
      <!-- Post Modern-->
      <article class="post post-modern post-modern-classic">
        <!-- Post media-->
        <header class="post-media"><%= image_tag article.article_photo, width:"370", height:"240", class:"img-responsive img-cover" %>
        </header>
        <!-- Post content-->
        <section class="post-content text-left">
          <!-- Post Title-->
          <div class="post-title offset-top-8">
            <h4 class="text-bold"> <%= link_to article.article_title, profile_article_path(@profile, article)%> </h4>
          </div>
          <ul class="list-inline list-inline-dashed">
            <li><%= article.created_at.strftime("%d.%m.%Y") %></li>
            <li><i  class="text-secondary"><%=article.theme%></i></li>
          </ul>
          <!-- Post Body-->
          <div class="post-body" style="margin-bottom: 30px;">
            <p><%= article.article_content.first(200) %> ...</p>
          </div>
        </section>
      </article>
    </div>
  <% end  %>
<% end %>

app/views/shared/_articlessante.html.erb
<% i = 0  %>
<% if Article.where(theme: "Santé et handicap") == [] %>
  <div class="cell-sm-6">
    <!-- Post Modern-->
    <article class="post post-modern post-modern-classic">
      <section class="post-content text-left">
        <!-- Post Title-->
        <div class="post-title offset-top-8">
          <p class="text-bold">Aucun article de cette catégorie n'a été rédigé pour le moment</p>
        </div>
      </section>
    </article>
  </div>
<% end  %>
<% @articles.where(status: 'Validé').order("created_at DESC").each do |article| %>
  <% if article.theme == "Santé et handicap" && i < 3 %>
    <% i = i + 1  %>
    <% @profile = Profile.find(article.profile_id)  %>
    <div class="cell-sm-6">
      <!-- Post Modern-->
      <article class="post post-modern post-modern-classic">
        <!-- Post media-->
        <header class="post-media"><%= image_tag article.article_photo, width:"370", height:"240", class:"img-responsive img-cover" %>
        </header>
        <!-- Post content-->
        <section class="post-content text-left">
          <!-- Post Title-->
          <div class="post-title offset-top-8">
            <h4 class="text-bold"> <%= link_to article.article_title, profile_article_path(@profile, article)%> </h4>
          </div>
          <ul class="list-inline list-inline-dashed">
            <li><%= article.created_at.strftime("%d.%m.%Y") %></li>
            <li><i  class="text-secondary"><%=article.theme%></i></li>
          </ul>
          <!-- Post Body-->
          <div class="post-body" style="margin-bottom: 30px;">
            <p><%= article.article_content.first(200) %> ...</p>
          </div>
        </section>
      </article>
    </div>
  <% end  %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert" style="margin: 0px">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert" style="margin: 0px">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="page text-center">
  <!-- Page Header-->
  <header class="page-head">
    <!-- RD Navbar minimal-->
    <div class="rd-navbar-wrap">
      <nav data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static" data-md-stick-up-offset="120px" data-lg-stick-up-offset="120px" class="rd-navbar rd-navbar-minimal rd-navbar-light " data-lg-auto-height="true" data-md-layout="rd-navbar-static" data-lg-layout="rd-navbar-static" data-lg-stick-up="true">
        <div class="rd-navbar-inner">
          <div class="rd-navbar-top-panel">
            <!--Navbar Brand-->
            <div class="rd-navbar-brand veil reveal-md-inline-block"><a href="/" class="veil reveal-lg-inline-block"><%= cl_image_tag "d595b7_a2b7f4d6f3504368ba7822b3d48b9a46-mv2_fotrsm.png", :height=>99, :crop=>"scale" , class:'img-responsive' %></a></div>
            <div>
              <!-- Contact Info-->
              <address class="contact-info reveal-sm-inline-block text-left offset-none">
                <div class="p unit unit-spacing-xs unit-horizontal">
                  <div class="unit-left"><span class="icon icon-xs icon-circle icon-java-filled mdi mdi-phone"></span></div>
                  <div class="unit-body"><a class="text-gray-darker" style="text-decoration: none">06.24.48.44.75</a><br/><a class="text-gray-darker" style="text-decoration: none">info@handipulse.fr</a></div>
                </div>
              </address>
              <!-- Contact Info-->
              <address class="contact-info reveal-sm-inline-block text-left">
                <div class="p unit unit-horizontal unit-spacing-xs">
                  <div class="unit-left"><span class="icon icon-xs icon-circle icon-java-filled mdi mdi-map-marker"></span></div>
                  <div class="unit-body"><a class="text-gray-darker" style="text-decoration: none">10 rue du Petit Boulevard BP 20127<br/>59653 Villeneuve d'Ascq Cedex</a></div>
                </div>
              </address>
            </div>
          </div>
          <!-- RD Navbar Panel-->
          <div class="rd-navbar-panel">
            <!-- RD Navbar Toggle-->
            <button data-rd-navbar-toggle=".rd-navbar, .rd-navbar-nav-wrap" class="rd-navbar-toggle"><span></span></button>
            <!--Navbar Brand-->
            <div class="rd-navbar-brand veil-md"><a href="/"><%= image_tag "logo-dark.png", width:'160', height:'45', class:'img-responsive' %></a></div>
<!--             <button data-rd-navbar-toggle=".rd-navbar, .rd-navbar-top-panel" class="rd-navbar-top-panel-toggle"><span></span></button> -->
          </div>
          <div class="rd-navbar-menu-wrap">
            <div class="rd-navbar-nav-wrap">
              <div class="rd-navbar-mobile-scroll">
                <!--Navbar Brand Mobile-->
                <div class="rd-navbar-mobile-brand"><a href="/"><%= cl_image_tag "d595b7_a2b7f4d6f3504368ba7822b3d48b9a46-mv2_fotrsm.png", :width=>100, :height=>100, :crop=>"scale" , class:'img-responsive' %></a></div>
                <!-- RD Navbar Nav-->
                <ul class="rd-navbar-nav">
                  <li class="<%= is_active?(root_path) %>"><%= link_to 'Accueil', root_path %>
                  </li>
                  <li class="<%= is_active?(pages_about_path) %>"><%= link_to 'A propos', pages_about_path %>
                  </li>
                  <li class="<%= is_active?(pages_all_articles_categories_path) %>"><%= link_to 'News', articles_all_path %>
                  </li>
                  <li class="<%= is_active?(profiles_path) %> <%= is_active?(pages_soins_path) %>"><%= link_to 'Se soigner', profiles_path %>
                    <div class="rd-navbar-megamenu">
                      <div class="row">
                        <div class="col-md-4">
                          <h6>Notre but est d'améliorer l'offre de soins</h6>
                          <hr class="text-subline"/>
                          <ul class="list-unstyled offset-lg-top-25">
                            <li><%= link_to 'Cabinets dentaires libéraux', profiles_path %></li>
                            <li><%= link_to 'Soins spécifiques en USOS', pages_soins_path %></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="<%= is_active?(pages_formation_path) %>"><%= link_to 'Formation / Prévention', pages_formation_path %>
                  </li>
                  <li class="<%= is_active?(pages_partnerships_path) %><%= is_active?(pages_make_a_donation_path) %><%= is_active?(pages_support_us_path) %>"><%= link_to 'Partenaires', pages_partnerships_path %>
                    <div class="rd-navbar-megamenu">
                      <div class="row">
                        <div class="col-md-4">
                          <h6>Faites partie de l'aventure Handident</h6>
                          <hr class="text-subline"/>
                          <ul class="list-unstyled offset-lg-top-25">
                            <li> <%= link_to 'Faites un don', pages_make_a_donation_path %></li>
                            <li> <%= link_to 'Entreprises, soutenez-nous !', pages_support_us_path %></li>
                            <li> <%= link_to 'Nos partenaires', pages_partnerships_path %></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="<%= is_active?(contacts_path) %>"><%= link_to 'Contact', contacts_path %>
                  </li>
                  <li>
                    <% if user_signed_in? %>
                      <% if current_user && current_user.profile %>
                        <li class="<%= is_active?(profile_path(current_user.profile)) %><%= is_active?(edit_profile_path(current_user.profile)) %> "><%= link_to 'Mon Compte', profile_path(current_user.profile) %>
                          <div class="rd-navbar-megamenu">
                            <div class="row">
                              <div class="col-md-4">
                                <h6> Bonjour <%= current_user.profile.first_name %></h6>
                                <hr class="text-subline"/>
                                <ul class="list-unstyled offset-lg-top-25">
                                  <li><%= link_to 'Voir mon profil', profile_path(current_user.profile) %></li>
                                  <li> <%= link_to 'Editer mon profil', edit_profile_path(current_user.profile) %></li>
                                  <li> <%= link_to 'Se déconnecter', destroy_user_session_path, :method => 'delete' %></li>
                                </ul>
                              </div>
                            </div>
                          </div>
                        </li>
                      <% else %>
                        <li class="<%= is_active?(new_profile_path) %>"><%= link_to 'Mon Compte' %>
                          <div class="rd-navbar-megamenu">
                            <div class="row">
                              <div class="col-md-4">
                                <h6>Mes données</h6>
                                <hr class="text-subline"/>
                                <ul class="list-unstyled offset-lg-top-25">
                                  <li><%= link_to 'Créer mon profil', new_profile_path %></li>
                                  <li><%= link_to 'Se déconnecter', destroy_user_session_path, :method => 'delete' %></li>
                                </ul>
                              </div>
                            </div>
                          </div>
                        </li>
                      <% end %>
                    <% else %>
                      <li class="<%= is_active?(new_user_session_path) %><%= is_active?(new_user_registration_path) %><%= is_active?(new_user_password_path) %>"><%= link_to 'Me connecter', new_user_session_path %>
                      </li>
                    <% end %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </div>
    <!-- Modern Breadcrumbs-->
    <section class="breadcrumb-modern context-dark text-md-left">
      <div class="shell section-34 section-md-top-200 section-md-bottom-41">
        <% if current_page?(pages_about_path) %>
          <h1 class="text-regular">A propos</h1>
        <% elsif current_page?(profiles_path) %>
          <h1 class="text-regular">Les dentistes partenaires</h1>
        <% elsif current_page?(pages_formation_path) %>
          <h1 class="text-regular">Formation et prévention</h1>
        <% elsif current_page?(pages_make_a_donation_path) %>
          <h1 class="text-regular">Faites un don</h1>
        <% elsif current_page?(pages_support_us_path) %>
          <h1 class="text-regular">Entreprise, aidez-nous !</h1>
        <% elsif current_page?(pages_partnerships_path) %>
          <h1 class="text-regular">Nos partenaires</h1>
        <% elsif current_page?(contacts_path) %>
          <h1 class="text-regular">Contactez-nous !</h1>
        <% elsif current_page?(pages_soins_path) %>
          <h1 class="text-regular">Améliorer l'offre de soins</h1>
        <% elsif current_page?(articles_all_path) %>
          <h1 class="text-regular">Tous les articles</h1>
        <% else  %>
          <h1 class="text-regular"></h1>
        <% end  %>
      </div>
    </section>
  </header>
</div>

app/views/shared/_navbarhome.html.erb
<!-- Page-->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


    <div id="wrapper">
        <div class="overlay"></div>

        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
            <ul class="nav sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                       HANDIPULSE
                    </a>
                </li>
                 <li><%= link_to 'A propos', pages_about_path, class: 'btn btn-rounded'%></li>
                    <li><%= link_to 'News', articles_all_path, class: 'btn btn-rounded'%></p>
                    <li><%= link_to 'Se soigner', profiles_path, class: 'btn btn-rounded'%></li>
                    <li><%= link_to 'Formation', pages_formation_path, class: 'btn btn-rounded'%></li>
                    <li><%= link_to 'Partenaires', pages_partnerships_path, class: 'btn btn-rounded'%></li>
                    <li><%= link_to 'Contact', contacts_path, class: 'btn btn-rounded'%></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="text-transform: uppercase">Mon compte <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li class="dropdown-header"></li>
                    <% if current_user && current_user.profile == nil%>
                          <li><%= link_to 'Créer mon profil', new_profile_path, class: 'btn btn-rounded'%></li>
                          <li><%= link_to 'Se déconnecter', destroy_user_session_path, :method => 'delete' %></li>
                        <% elsif current_user && current_user.profile %>
                          <li><%= link_to 'Voir mon profil', profile_path(current_user.profile), class: 'btn btn-rounded'%></li>
                          <li><%= link_to 'Editer mon profil', edit_profile_path(current_user.profile), class: 'btn btn-rounded'%></li>
                          <li><%= link_to 'Faire un don', new_profile_donation_path(current_user.profile), class: 'btn btn-rounded'%></li>
                          <li> <%= link_to 'Se déconnecter', destroy_user_session_path, :method => 'delete' , class: 'btn btn-rounded'%></li>
                        <% else %>
                          <li> <%= link_to 'Me connecter', new_user_session_path %>
                          </li>
                        <% end %>
                  </ul>
                </li>

            </ul>
        </nav>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
                <span class="hamb-top"></span>
          <span class="hamb-middle"></span>
        <span class="hamb-bottom"></span>
            </button>

        </div>
        <!-- /#page-content-wrapper -->

    </div>

    <style>
body {
    position: relative;
    overflow-x: hidden;
}
body,
html { height: 100%;}
.nav .open > a,
.nav .open > a:hover,
.nav .open > a:focus {background-color: transparent;}



#wrapper {
    padding-left: 0;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
}

#wrapper.toggled {
    padding-left: 220px;
}

#sidebar-wrapper {
    z-index: 1000;
    left: 220px;
    width: 0;
    height: 100%;
    margin-left: -220px;
    overflow-y: auto;
    overflow-x: hidden;
    background: #fff;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
}

#sidebar-wrapper::-webkit-scrollbar {
  display: none;
}

#wrapper.toggled #sidebar-wrapper {
    width: 220px;
}

#page-content-wrapper {
    width: 100%;
    padding-top: 70px;
}

#wrapper.toggled #page-content-wrapper {
    position: absolute;
    margin-right: -220px;
}



.sidebar-nav {
    position: absolute;
    top: 0;
    width: 220px;
    margin: 0;
    padding: 0;
    list-style: none;
}

.sidebar-nav li {
    position: relative;
    line-height: 20px;
    display: inline-block;
    width: 100%;
}

.sidebar-nav li:before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    z-index: -1;
    height: 100%;
    width: 3px;
    background-color: #9FBF49;
    -webkit-transition: width .2s ease-in;
      -moz-transition:  width .2s ease-in;
       -ms-transition:  width .2s ease-in;
            transition: width .2s ease-in;

}
.sidebar-nav li:first-child a {
    color: #434445;
    background-color: ##9FBF49;
}
.sidebar-nav li:nth-child(2):before {
    background-color: ##9FBF49;
}
.sidebar-nav li:nth-child(3):before {
    background-color: ##9FBF49;
}
.sidebar-nav li:nth-child(4):before {
    background-color: #9FBF49;
}
.sidebar-nav li:nth-child(5):before {
    background-color: #9FBF49;
}
.sidebar-nav li:nth-child(6):before {
    background-color: #9FBF49;
}
.sidebar-nav li:nth-child(7):before {
    background-color: #9FBF49;
}
.sidebar-nav li:nth-child(8):before {
    background-color: #9FBF49;
}
.sidebar-nav li:nth-child(9):before {
    background-color: #9FBF49;
}
.sidebar-nav li:hover:before,
.sidebar-nav li.open:hover:before {
    width: 100%;
    -webkit-transition: width .2s ease-in;
      -moz-transition:  width .2s ease-in;
       -ms-transition:  width .2s ease-in;
            transition: width .2s ease-in;

}

.sidebar-nav li a {
    display: block;
    color: #434445;
    text-decoration: none;
    padding: 10px 15px 10px 30px;
}

.sidebar-nav li a:hover,
.sidebar-nav li a:active,
.sidebar-nav li a:focus,
.sidebar-nav li.open a:hover,
.sidebar-nav li.open a:active,
.sidebar-nav li.open a:focus{
    color: #red;
    text-decoration: none;
    background-color: transparent;
}

.sidebar-nav > .sidebar-brand {
    height: 65px;
    font-size: 20px;
    line-height: 44px;
}
.sidebar-nav .dropdown-menu {
    position: relative;
    width: 100%;
    padding: 0;
    margin: 0;
    border-radius: 0;
    border: none;
    background-color: #blue;
    box-shadow: none;
}



.hamburger {
  position: fixed;
  top: 20px;
  z-index: 999;
  display: block;
  width: 32px;
  height: 32px;
  margin-left: 15px;
  background: transparent;
  border: none;
}
.hamburger:hover,
.hamburger:focus,
.hamburger:active {
  outline: none;
}
.hamburger.is-closed:before {
  content: '';
  display: block;
  width: 100px;
  font-size: 14px;
  color: red;
  line-height: 32px;
  text-align: center;
  opacity: 0;
  -webkit-transform: translate3d(0,0,0);
  -webkit-transition: all .35s ease-in-out;
}
.hamburger.is-closed:hover:before {
  opacity: 1;
  display: block;
  -webkit-transform: translate3d(-100px,0,0);
  -webkit-transition: all .35s ease-in-out;
}

.hamburger.is-closed .hamb-top,
.hamburger.is-closed .hamb-middle,
.hamburger.is-closed .hamb-bottom,
.hamburger.is-open .hamb-top,
.hamburger.is-open .hamb-middle,
.hamburger.is-open .hamb-bottom {
  position: absolute;
  left: 0;
  height: 4px;
  width: 100%;
}
.hamburger.is-closed .hamb-top,
.hamburger.is-closed .hamb-middle,
.hamburger.is-closed .hamb-bottom {
  background-color: #1a1a1a;
}
.hamburger.is-closed .hamb-top {
  top: 5px;
  -webkit-transition: all .35s ease-in-out;
}
.hamburger.is-closed .hamb-middle {
  top: 50%;
  margin-top: -2px;
}
.hamburger.is-closed .hamb-bottom {
  bottom: 5px;
  -webkit-transition: all .35s ease-in-out;
}

.hamburger.is-closed:hover .hamb-top {
  top: 0;
  -webkit-transition: all .35s ease-in-out;
}
.hamburger.is-closed:hover .hamb-bottom {
  bottom: 0;
  -webkit-transition: all .35s ease-in-out;
}
.hamburger.is-open .hamb-top,
.hamburger.is-open .hamb-middle,
.hamburger.is-open .hamb-bottom {
  background-color: #1a1a1a;
}
.hamburger.is-open .hamb-top,
.hamburger.is-open .hamb-bottom {
  top: 50%;
  margin-top: -2px;
}
.hamburger.is-open .hamb-top {
  -webkit-transform: rotate(45deg);
  -webkit-transition: -webkit-transform .2s cubic-bezier(.73,1,.28,.08);
}
.hamburger.is-open .hamb-middle { display: none; }
.hamburger.is-open .hamb-bottom {
  -webkit-transform: rotate(-45deg);
  -webkit-transition: -webkit-transform .2s cubic-bezier(.73,1,.28,.08);
}
.hamburger.is-open:before {
  content: '';
  display: block;
  width: 100px;
  font-size: 14px;
  color: #fff;
  line-height: 32px;
  text-align: center;
  opacity: 0;
  -webkit-transform: translate3d(0,0,0);
  -webkit-transition: all .35s ease-in-out;
}
.hamburger.is-open:hover:before {
  opacity: 1;
  display: block;
  -webkit-transform: translate3d(-100px,0,0);
  -webkit-transition: all .35s ease-in-out;
}



.overlay {
    position: fixed;
    display: none;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(250,250,250,.8);
    z-index: 1;
}
  </style>
  <script>
$(document).ready(function () {
  var trigger = $('.hamburger'),
      overlay = $('.overlay'),
     isClosed = false;

    trigger.click(function () {
      hamburger_cross();
    });

    function hamburger_cross() {

      if (isClosed == true) {
        overlay.hide();
        trigger.removeClass('is-open');
        trigger.addClass('is-closed');
        isClosed = false;
      } else {
        overlay.show();
        trigger.removeClass('is-closed');
        trigger.addClass('is-open');
        isClosed = true;
      }
  }

  $('[data-toggle="offcanvas"]').click(function () {
        $('#wrapper').toggleClass('toggled');
  });
});
  </script>