config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users

  resources :profiles do
    resources :articles
    resources :donations
    resources :reviews
    resources :meetings
    resources :messages
  end
  resources :orders, only: [:show, :new, :create] do
    resources :payments, only: [:new, :create]
  end
  resources :charges
  root to: 'pages#home'
  get 'citywithdept', to: 'profiles#citywithdept'
  get 'dentistwithcity', to: 'profiles#dentistwithcity'
  get 'getSearch', to: 'profiles#getSearch'

  get 'excelcreator', to: 'profiles#excelcreator'

  get 'valider_article', to: 'articles#valider_article'
  get 'refuser_article', to: 'articles#refuser_article'
  get 'valider_review', to: 'reviews#valider_review'
  get 'refuser_review', to: 'reviews#refuser_review'
  get 'pages/about'
  get 'pages/formation'
  get 'pages/formation1'
  get 'pages/test'
  get 'pages/partnerships'
  get 'reviews/all'
  get 'articles/all'
  get 'pages/soins'
  get 'pages/all_articles_categories'
  get 'pages/make_a_donation'
  get 'pages/support_us'
  get 'pages/conversation'
  get 'pages/demande_rdv'
  get 'pages/conversationitem'

  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    if current_user == nil
      redirect_to new_user_session_path
      flash[:alert] = 'Merci créer votre compte avant de publier un avis'
    else
      @profile = current_user.profile
    end
  end

  def create
    @review = Review.new(review_params)
    @profile = current_user.profile
    @review.profile = @profile
    @review.review_status = "A valider"
    admin = "staumont.antoine@me.com"
    if @review.save
      MessageMailer.mail_admin_review(admin).deliver_now
      redirect_to root_path
      flash[:notice] = 'Merci pour votre commentaire !'
    else
      render :new
      flash[:notice] = 'Une erreur est survenue, veuillez recommencer ...'
    end
  end

  def all
    @reviews =Review.where(review_status: 'Validé')
  end

  def valider_review
    @review = Review.find(params[:reviewid])
    @profile = Profile.find(params[:profileid])
    @review.review_status = "Validé"
    @review.save
    flash[:notice] = "Le témoignage a été validé. Merci."
    redirect_to reviews_all_path
  end

  def refuser_review
    @review = Review.find(params[:reviewid])
    @profile = Profile.find(params[:profileid])
    @review.review_status = "Refusé"
    @review.save
    flash[:alert] = "Le témoignage a été refusé."
    redirect_to reviews_all_path
  end

  private

  def review_params
    params.require(:review).permit(:review_title, :review_content, :rating)

  end
end

app/views/reviews/all.html.erb
<!-- Page-->
<div class="page text-center">
  <!-- Page Contents-->
  <main class="page-content">
    <!-- Modern Blog-->
    <div id="fb-root"></div>
    <section class="section-98 section-sm-110 text-left">
      <div class="shell">
        <div class="range range-xs-center range-lg-right">
          <div class="cell-sm-10 cell-md-8">
            <div class="offset-top-30 offset-md-top-66" style="margin-top: 0px">
              <div class="clearfix"></div>
              <div class="offset-top-66">
                <h3>Ce que vous pensez de nous</h3>
                <hr class="text-subline">
              </div>
              <% Review.where(review_status: 'Validé').each do |review| %>
                <% @profile = Profile.find(review.profile_id)  %>
                <div class="offset-top-30">
                  <div class="unit unit-xs unit-xs-horizontal">
                    <% if review.profile.photo_url.nil? %>
                      <div class="unit-left"><%= image_tag "http://res.cloudinary.com/dz83jh064/image/upload/v1517825470/images_z0whi1.png", width:'170', height:'170', class:'img-circle img-responsive center-block' %></div>
                    <% else  %>
                      <div class="unit-left"><%= image_tag Profile.find(review.profile_id).photo, width:'170', height:'170', class:'img-circle img-responsive center-block' %></div>
                    <% end %>
                    <div class="unit-body text-xs-left">
                      <div>
                        <h4><a><%= link_to @profile.first_name, profile_path(@profile), class: 'text-primary' %> <%= link_to @profile.last_name, profile_path(@profile), class: 'text-primary' %></a></h4>
                      </div>
                      <div class="offset-top-4 offset-sm-top-8">
                        <div class="text-gray text-italic"><%= review.review_title %></div>
                      </div>
                      <div class="offset-top-20 text-left">
                        <p class="text-gray-darker"><%= review.review_content %></p>
                      </div>
                    </div>
                  </div>
                </div>
              <% end  %>
            </div>
          </div>
          <div class="cell-sm-10 cell-md-4 offset-top-66 offset-md-top-0">
            <div class="blog-grid-sidebar inset-xl-left-30">
              <!-- Aside-->
              <aside class="text-left">
                <!-- Archive-->
              <div class="offset-top-66">
                <h3>Quelques renseignements ?</h3>
                <hr class="text-subline">
              </div>
                <div class="offset-top-14 offset-md-top-20">
                  <div class="range range-xs-center range-lg-left">
                    <%= link_to "Voir la charte", "/charte.pdf", target: "_blank", class:"btn-fullwidth btn btn-white btn-ellipse", style:"margin-top:20px"%>
                    <%= link_to "Voir la plaquette", "/plaquette.pdf", target: "_blank", class:"btn-fullwidth btn btn-white btn-ellipse", style:"margin-top:20px"%>
                    <%= link_to 'Nous contacter', contacts_path, class: 'btn-fullwidth btn btn-white btn-ellipse', style:"margin-top:20px"%>
                    <%= link_to 'Poster un avis sur Handident', new_profile_review_path(:profile_id), class: 'btn-fullwidth btn btn-primary btn-ellipse', style:"margin-top:20px;"%>
                  </div>
                </div>
              </aside>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</div>

app/views/reviews/new.html.erb
<!-- Page-->
<div class="page text-center">
  <!-- Page Content-->
  <main class="page-content section-top-98 section-sm-top-110">
    <!-- Get In Touch-->
    <section>
      <div class="shell">
        <div class="range range-xs-center">
          <div class="cell-sm-9 cell-md-8 cell-lg-12">
            <div class="range">
              <div class="cell-lg-8 text-left">
                <h2>Publier un témoignage</h2>
                <hr class="divider divider-lg bg-secondary hr-left-0 hr-sm-left-2">
                <div class="offset-top-34">
                  <%= simple_form_for [@profile, @review] do |f| %>
                    <form data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php" novalidate="novalidate" class="rd-mailform text-left">
                      <div class="range range-xs-center">
                        <div class="cell-sm-6">
                          <div class="form-group form-group-label-outside">
                            <%= f.input :review_title ,label: 'Donnez un titre à votre témoignage:', id:"contacts-last-name", type:"text", name:"Adresse", required: true, class: "form-control form-control-last-child" %>
                          </div>
                        </div>
                        <div class="cell-sm-6 offset-top-20 offset-sm-top-0">
                          <div class="form-group form-group-label-outside">
                            <%= f.input :rating, collection: 1..5,label: 'Evaluez nous de 1 à 5:', id:"contacts-last-name", type:"text", name:"Adresse", required: true, class: "form-control form-control-last-child" %>
                          </div>
                        </div>
                        <div class="cell-sm-12">
                          <div class="form-group form-group-label-outside offset-top-20">
                            <%= f.input :review_content ,label: 'Votre témoignage:', id:"contacts-message", :as => :text, input_html: {style: 'max-height:1500px;'}, required: true, class: "form-control form-control-last-child" %>
                          </div>
                        </div>
                      </div>
                      <div class="offset-top-18 offset-sm-top-24 text-center text-sm-left">
                        <div class="group-lg offset-top-20 offset-md-top-30">
                          <%= f.button :submit, class:"btn-fullwidth btn btn-ellipse btn-primary", style:"font-weight:bold", value:"Pubier mon témoignage" %>
                          <p><%= link_to 'Annuler', profile_path(current_user.profile), class:'btn-fullwidth btn btn-ellipse btn-white', style:"margin-top:20px"%></p>
                        </div>
                      </div>
                    </form>
                  <% end %>
                </div>
              </div>
              <div class="cell-lg-4 text-left offset-top-66 offset-lg-top-0">
                <div class="inset-lg-left-40">
                  <div>
                    <h4>Liens sociaux</h4>
                    <hr class="text-subline">
                      <ul class="list-inline">
                        <li><a href="https://fr-fr.facebook.com/handident/" target="_blank" class="icon fa fa-facebook icon-xxs icon-circle icon-gray-light"></a></li>
                        <li><a href="https://twitter.com/handidentoff" target="_blank" class="icon fa fa-twitter icon-xxs icon-circle icon-gray-light"></a></li>
                        <li><a href="https://www.youtube.com/channel/UCgVsiGM8NqG5VBQ9j_ZBjTQ" target="_blank" class="icon fa fa-google icon-xxs icon-circle icon-gray-light"></a></li>
                      </ul>
                  </div>
                  <div class="offset-top-60">
                    <h4>Adresse</h4>
                    <hr class="text-subline">
                    <div class="offset-top-20">
                      <div class="unit unit-horizontal unit-spacing-xxs p">
                        <div class="unit-left">
                          <div class="icon icon-xxs text-middle mdi mdi-map-marker text-secondary"></div>
                        </div>
                        <div class="unit-body">
                          <p><a class="text-gray-dark" style="text-decoration: none;">10 rue du Petit Boulevard BP 20127<br>59653 Villeneuve d'Ascq Cedex</a></p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="offset-top-60">
                    <h4>Heures d'ouverture</h4>
                    <hr class="text-subline">
                    <div class="offset-top-20">
                      <div class="unit unit-horizontal unit-spacing-xxs p">
                        <div class="unit-left">
                          <div class="icon icon-xxs text-middle mdi mdi-calendar-clock text-secondary"></div>
                        </div>
                        <div class="unit-body">
                          <div class="text-gray-dark">Lun-Ven: 08:00–18:00</div>
                          <div class="text-gray-dark">WE: Fermé</div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="offset-top-60">
                    <h4>Téléphone</h4>
                    <hr class="text-subline">
                    <div class="offset-top-20">
                      <div class="unit unit-horizontal unit-spacing-xxs p">
                        <div class="unit-left">
                          <div class="icon icon-xxs text-middle mdi mdi-phone text-secondary"></div>
                        </div>
                        <div class="unit-body"><a class="text-dark reveal-block">+33.3.28.80.7.86</a></div>
                      </div>
                    </div>
                  </div>
                  <div class="offset-top-60">
                    <h4>E-mail</h4>
                    <hr class="text-subline">
                    <div class="offset-top-20">
                      <div class="unit unit-horizontal unit-spacing-xxs p">
                        <div class="unit-left">
                          <div class="icon icon-xxs text-middle mdi mdi-email-outline text-secondary"></div>
                        </div>
                        <div class="unit-body"><a href="mailto:#" class="text-dark">Hello@handident.com</a></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="offset-top-110">
            <!-- RD Google Map-->
    <div id="map" style="width: 100%; height: 400px;"></div>
    <% content_for(:after_js) do %>
      <%= javascript_tag do %>
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(
          [
            {
              "lat": 50.626831,
              "lng": 3.144445,
              "infowindow": "<p>10 rue du Petit Boulevard, 59653 Villeneuve d'Ascq</p>"
            },
          ]
        );
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if (markers.length == 0) {
            handler.getMap().setZoom(2);
          } else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
        });
      <% end %>
    <% end %>
      </div>
    </section>
  </main>
</div>